add

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -280,52 +280,6 @@ jobs:
       - slack/notify:
           event: fail
           template: basic_fail_1     
-
-  smoke-test:
-    docker:
-      # Lightweight Docker image 
-      - image: amazon/aws-cli
-    steps:
-      # Checkout code from git
-      - checkout
-      - run:
-          name: Install dependencies
-          command: |
-            # your code here
-            yum install -y curl
-      - run:
-          name: Backend Smoke Test
-          command: |
-            # your code here
-            export BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:project,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" --output text)
-            export API_URL="http://${BACKEND_IP}:3030"
-            sleep 120
-            echo "${API_URL}"
-            if curl -s "${API_URL}/api/status" | grep "ok"
-            then
-              exit 0
-            else
-              exit 0
-            fi
-      - run:
-          name: Frontend smoke test.
-          command: |
-            # your code here          
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"  
-            echo ${URL} 
-            if curl -s ${URL} | grep "Welcome"
-            then
-            # Change this to 0 after the job fails
-              exit 0
-            else
-              exit 1
-            fi
-      # Here's where you will add some code to rollback on failure  
-      - revert-migrations
-      - destroy-environment  
-      - slack/notify:
-          event: fail
-          template: basic_fail_1      
   
   deploy-backend:
     docker:
@@ -379,6 +333,52 @@ jobs:
           event: fail
           template: basic_fail_1    
 
+  smoke-test:
+    docker:
+      # Lightweight Docker image 
+      - image: amazon/aws-cli
+    steps:
+      # Checkout code from git
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            # your code here
+            yum install -y curl
+      - run:
+          name: Backend Smoke Test
+          command: |
+            # your code here
+            export BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:project,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            sleep 120
+            echo "${API_URL}"
+            if curl -s "${API_URL}/api/status" | grep "ok"
+            then
+              exit 0
+            else
+              exit 0
+            fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+            # your code here          
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"  
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+            # Change this to 0 after the job fails
+              exit 0
+            else
+              exit 1
+            fi
+      # Here's where you will add some code to rollback on failure  
+      - revert-migrations
+      - destroy-environment  
+      - slack/notify:
+          event: fail
+          template: basic_fail_1      
+
 workflows:
   default:
     jobs:
@@ -402,3 +402,5 @@ workflows:
             requires: [run-migrations]
         - deploy-backend:
             requires: [run-migrations]
+        - smoke-test:
+            requires: [deploy-backend, deploy-frontend]
